# Свойства матричных вычислений: 

## Транспонирование

In [3]:
import numpy as np
A = np.matrix('3 3 3; 4 4 4')
print(A.T)

[[3 4]
 [3 4]
 [3 4]]


Свойство 1. Транспонированная матрица равна исходнйо матрице.

In [5]:
A = np.matrix('3 3 3; 4 4 4')
E = (A.T).T
print(E)

[[3 3 3]
 [4 4 4]]


Свойство 2. Транспоринование суммы матриц равно сумме транспонированных матриц.

In [10]:
A = np.matrix('8 7 6; 5 4 3')
B = np.matrix('1 2 3; 5 5 5')
L = (A + B).T
R = A.T + B.T
print("Транспонирование суммы:\n",L)
print("Сумма транспонированных матриц:\n",R)

Транспонирование суммы:
 [[ 9 10]
 [ 9  9]
 [ 9  8]]
Сумма транспонированных матриц:
 [[ 9 10]
 [ 9  9]
 [ 9  8]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке.

In [12]:
A = np.matrix('7 2; 7 4')
B = np.matrix('7 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print("Транспонирование произведения матриц:\n",L)
print("Произведение транспонированных матриц расставленных в обратном порядке:\n",R)

Транспонирование произведения матриц:
 [[63 77]
 [58 74]]
Произведение транспонированных матриц расставленных в обратном порядке:
 [[63 77]
 [58 74]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу.

In [13]:
A = np.matrix('1 2 3; 4 5 6')
k = 100
L = (k * A).T
R = k * (A.T)
print("Транспонирование произведения матрицы на число:\n",L)
print("Произведение этого числа на транспонированную матрицу:\n",R)

Транспонирование произведения матрицы на число:
 [[100 400]
 [200 500]
 [300 600]]
Произведение этого числа на транспонированную матрицу:
 [[100 400]
 [200 500]
 [300 600]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают.

In [17]:
A = np.matrix('88 100; 1 8')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print("Определитель исходной матрицы:",format(A_det, '.9g'))
-2
print("Определитель транспонированной матрицы:",format(A_T_det, '.9g'))

Определитель исходной матрицы: 604
Определитель транспонированной матрицы: 604


## Умножение

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице.

In [19]:
A = np.matrix('1 2; 3 4')
L = 1 * A
print("Матрица умноженная на единицу:\n", L)

Матрица умноженная на единицу:
 [[1 2]
 [3 4]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы.

In [20]:
A = np.matrix('1 2; 3 4')
L = 0 * A
print("Произведение матрицы на ноль:\n", L)

Произведение матрицы на ноль:
 [[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел.

In [21]:
A = np.matrix('1 2; 1 2')
p = 100
q = 5
L = (p + q) * A
R = p * A + q * A
print("Произведение матрицы на сумму чисел:\n", L)
print("Сумма произведений матрицы на каждое из этих чисел:\n", R)

Произведение матрицы на сумму чисел:
 [[105 210]
 [105 210]]
Сумма произведений матрицы на каждое из этих чисел:
 [[105 210]
 [105 210]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число.

In [22]:
A = np.matrix('1 2; 1 2')
p = 2
q = 100
L = (p * q) * A 
R = p * (q * A)
print("Произведение матрицы на произведение двух чисел:\n", L)
print("Произведение второго числа и заданной матрицы, умноженному на первое число:\n", R)

Произведение матрицы на произведение двух чисел:
 [[200 400]
 [200 400]]
Произведение второго числа и заданной матрицы, умноженному на первое число:
 [[200 400]
 [200 400]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число.

In [23]:
A = np.matrix('1 2; 1 2')
B = np.matrix('3 4; 5 5')
k = 100
L = k * (A + B)
R = k * A + k * B
print("Произведение суммы матриц на число:\n", L)
print("Сумма произведений этих матриц на заданное число:\n", R)

Произведение суммы матриц на число:
 [[400 600]
 [600 700]]
Сумма произведений этих матриц на заданное число:
 [[400 600]
 [600 700]]


## Сложение

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется.

In [24]:
A = np.matrix('1000 2000; 300 400')
B = np.matrix('500 600; 7000 8000')
L = A + B
R = B + A
print("Сумма А + В:\n", L)
print("Сумма В + А:\n", R)

Сумма А + В:
 [[1500 2600]
 [7300 8400]]
Сумма В + А:
 [[1500 2600]
 [7300 8400]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться.

In [25]:
A = np.matrix('1 1; 1 1')
B = np.matrix('2 2; 2 2')
C = np.matrix('3 3; 3 3')
L = A + (B + C)
R = (A + B) + C
print("Сумма A + (B + C):\n", L)
print("Сумма (A + B) + C:\n", R)

Сумма A + (B + C):
 [[6 6]
 [6 6]]
Сумма (A + B) + C:
 [[6 6]
 [6 6]]


Свойство 3. Для любой матрицы существует противоположная ей, такая, что их сумма является нулевой матрицей.

In [27]:
A = np.matrix('10000000 20000000; 30000000 40000000')
L = A + (-1)*A
print("Нулевая матрица:\n", L)

Нулевая матрица:
 [[0 0]
 [0 0]]


## Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция.

In [29]:
A = np.matrix('1 1; 1 1')
B = np.matrix('2 2; 2 2')
C = np.matrix('5 5; 5 5')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print("Произведение A * (B * C):\n", L)
print("Произведение (A * B) * C:\n", R)

Произведение A * (B * C):
 [[40 40]
 [40 40]]
Произведение (A * B) * C:
 [[40 40]
 [40 40]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц.

In [31]:
A = np.matrix('1 1; 1 1')
B = np.matrix('2 2; 2 2')
C = np.matrix('5 5; 5 5')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print("Произведение A * (B + C):\n", L)
print("Произведение A * B + A * C:\n", R)

Произведение A * (B + C):
 [[14 14]
 [14 14]]
Произведение A * B + A * C:
 [[14 14]
 [14 14]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей.

In [33]:
A = np.matrix('1 8; 10 1')
B = np.matrix('8 2; 2 12')
L = A.dot(B)
R = B.dot(A)
print("Произведение A * B:\n", L)
print("Произведение B * A:\n", R)

Произведение A * B:
 [[24 98]
 [82 32]]
Произведение B * A:
 [[ 28  66]
 [122  28]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице.

In [34]:
A = np.matrix('5 4; 1 8')
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print("Произведение заданной матрицы на единичную:\n", L)
print("Произведение единичной матрицы на заданную:\n", R)
print("Исходная матрица:\n", A)

Произведение заданной матрицы на единичную:
 [[1 2]
 [3 4]]
Произведение единичной матрицы на заданную:
 [[1 2]
 [3 4]]
Исходная матрица:
 [[1 2]
 [3 4]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице.

In [37]:
A = np.matrix('5 4; 1 8')
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print("Произведение заданной матрицы на нулевую:\n", L)
print("Произведение нулевой матрицы на заданную:\n", R)
print("Исходная матрица:\n", Z)

Произведение заданной матрицы на нулевую:
 [[0 0]
 [0 0]]
Произведение нулевой матрицы на заданную:
 [[0 0]
 [0 0]]
Исходная матрица:
 [[0 0]
 [0 0]]


## Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании.

In [42]:
A = np.matrix('1 10 2; 10 2 -1; 5 8 11')
R = A.T
det_A = round(np.linalg.det(A), 3)
det_R = round(np.linalg.det(R), 3)
print("Опеределитель матрицы:", det_A)
print("Определитель транспонированной матрицы:", det_R)

Опеределитель матрицы: -980.0
Определитель транспонированной матрицы: -980.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю.

In [43]:
A = np.matrix('1 10 2; 0 0 0; 5 8 11')
print("Опеределитель матрицы:", np.linalg.det(A))

Опеределитель матрицы: 0.0


Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный.

In [5]:
A = np.matrix('1 10 2; 10 2 -1; 5 8 11')
B = np.matrix('10 2 -1; 1 10 2; 5 8 11')
R = round(np.linalg.det(A), 3)
L = round(np.linalg.det(B), 3)
print("Определитель матрицы А:", R)
print("Определитель матрицы В:", L)

Определитель матрицы А: -980.0
Определитель матрицы В: 980.0


Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю.

In [46]:
A = np.matrix('1 10 2; 1 10 2; 5 8 11')
R = round(np.linalg.det(A), 3)
print("Определитель матрицы А:", R)

Определитель матрицы А: 0.0


Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число.

In [7]:
A = np.matrix('1 10 2; 1 11 2; 5 8 11')
k = 100
B[2, :] = k * B[2, :]
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print("Опеределитель матрицы:", det_A)
print("Определитель матрицы умноженной на число:", det_B)

Опеределитель матрицы: 1.0
Определитель матрицы умноженной на число: 9800000.0


Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц.

In [60]:
A = np.matrix('-1 -1 3; -1 -1 3; 2 2 3')
B = np.matrix('-1 -1 3; 2 2 7; 2 2 3')
C = A.copy()
C[1, :] += B[1, :]
R = round(np.linalg.det(C), 3)
L = round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)
print("Определитель матрицы C:", R)
print("Определитель суммы двух матриц:", L)

Определитель матрицы C: 0.0
Определитель суммы двух матриц: 0.0


Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится.

In [67]:
A = np.matrix('-1 -1 3; -1 0 3; 2 2 3')
k = 100
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
R = round(np.linalg.det(A), 3)
L = round(np.linalg.det(B), 3)
print("Определитель матрицы A:", R)
print("Определитель матрицы B:", L)

Определитель матрицы A: -9.0
Определитель матрицы B: -9.0


Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю.

In [68]:
A = np.matrix('-1 -1 3; -1 0 3; 2 2 3')
k = 100
A[1, :] = A[0, :] + k * A[2, :]
R = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", R)

Определитель матрицы A: -0.0


Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю.

In [70]:
A = np.matrix('-1 -1 3; -1 0 3; 2 2 3')
k = 100
A[1, :] = k * A[0, :]
R = round(np.linalg.det(A), 3)
print("Определитель матрицы A:", R)

Определитель матрицы A: 0.0


## Обратная матрица

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица.

In [72]:
A = np.matrix('8. -11.; 5. 4.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print("Определитель исходной матрицы:\n", A_inv)
print("Определитель обратной обратной матрицы A:\n", A_inv_inv)

Определитель исходной матрицы:
 [[ 0.04597701  0.12643678]
 [-0.05747126  0.09195402]]
Определитель обратной обратной матрицы A:
 [[  8. -11.]
 [  5.   4.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы.

In [73]:
A = np.matrix('8. -11.; 5. 4.')
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print("Обратная матрица транспонированной матрицы:\n",L)
print("Транспонированная матрица от обратной матрицы:\n", R)

Обратная матрица транспонированной матрицы:
 [[ 0.04597701 -0.05747126]
 [ 0.12643678  0.09195402]]
Транспонированная матрица от обратной матрицы:
 [[ 0.04597701 -0.05747126]
 [ 0.12643678  0.09195402]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц.

In [75]:
A = np.matrix('8. -11.; 5. 4.')
B = np.matrix('15. -7.; 22. 2.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print("Обратная матрица произведения матриц:\n",L)
print("Произведение обратных матриц:\n", R)

Обратная матрица произведения матриц:
 [[-0.00168666  0.00487256]
 [-0.01018241 -0.00762119]]
Произведение обратных матриц:
 [[-0.00168666  0.00487256]
 [-0.01018241 -0.00762119]]
